jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: .
          sonar.projectKey: ${{ secrets.SONAR_PROJECT_KEY }}  # Specify the project key here
          sonar.organization: ${{ secrets.SONAR_ORGANIZATION }}  # Specify the organization here
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: node-sample-demo:v2

      - name: Trivy scan image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: node-sample-demo:v2
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH
        continue-on-error: true  # optionally skip failing pipeline on scan failure

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/node-sample-demo:v2
